<?php

namespace SIAPEP\GocardlessBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * MandateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandateRepository extends EntityRepository
{
	
}