<?php

namespace SIAPEP\GocardlessBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{

	public function findSubscription($local_user)
	{
	    $query = $this->createQueryBuilder('i');
		
        $query  = $query ->select('i.id, i.gc_id')
                ->where("i.gc_status != 'invactive'")
                ->andWhere('i.local_user = '.$local_user)
		->orderBy('i.id', 'DESC')
		->getQuery();
        return $query->getResult();
	}
}